version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: python-dotenv
    versions:
    - 0.15.0
    - 0.16.0
  - dependency-name: alembic
    versions:
    - 1.5.2
    - 1.5.3
    - 1.5.4
    - 1.5.5
    - 1.5.6
    - 1.5.7
  - dependency-name: coverage
    versions:
    - "5.4"
  - dependency-name: flask-migrate
    versions:
    - 2.6.0
  - dependency-name: cffi
    versions:
    - 1.14.4
  - dependency-name: more-itertools
    versions:
    - 8.6.0
